version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=nazo123
      - POSTGRES_USER=nazo
      - POSTGRES_DB=blog
